/*Write a program to show the use of nested try statements that emphasizes the sequence of
  checking for catch handler statements.*/

package program19;

import java.util.Scanner;

class nestedTry{
   
   public static void main(String[] args){
      
      Scanner in=new Scanner(System.in);
      System.out.println("Enter a: ");
      int a=in.nextInt();
      
      try{
         /*If value of 'a' entered is 'zero'
           the following statement will generate 
           a divide-by-zero exceptio.*/
         int b=42/a;
         System.out.println("a = "+a);
         
         try{
            /*If value of 'a' entered is one,
              then a divide-by-zero exception
              will be generated by following code.*/
              
            if(a==1)
            a=a/(a-a);
            
            /*If the value entered is two,
              then the following code will generate
              a Array-Index-Out-Of-Bounds exception.*/
            if(a==2)
            {
               int c[]={1};
               c[42]=99;   //generate an out-of-bound exception
            }
           
           } catch(ArrayIndexOutOfBoundsException e){
            System.out.println("Array index out-of-bound: "+e);
           }
           
         } catch(ArithmeticException e){
               System.out.println("Divide by 0: "+e);
         }         
   }
}